<a href="https://colab.research.google.com/github/Alokkr00/Alokkr00/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Q. Try to create csv file from above method from pandas , also use reshape function to covert the 1 d array in to 2 d array.Example:(arr = np.arange(1,11).reshape(2,5))

In [3]:
import pandas as pd
import numpy as np

In [4]:
test=[1,2,3,4,5]

In [5]:
np.array(test)

array([1, 2, 3, 4, 5])

In [6]:
arr=np.array(test)

In [7]:
test1=[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]
test1

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]]

In [8]:
np.array(test1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [9]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.linspace(0,15,6)

array([ 0.,  3.,  6.,  9., 12., 15.])

In [14]:
np.random.rand(5)

array([0.38799298, 0.49822489, 0.32324734, 0.42987947, 0.74038885])

In [15]:
np.random.rand(5,5)

array([[0.67128615, 0.34429238, 0.78347103, 0.60651164, 0.94410769],
       [0.29360095, 0.90534405, 0.01616695, 0.61430432, 0.14714524],
       [0.84022776, 0.0254696 , 0.22510409, 0.72758879, 0.36248889],
       [0.38785577, 0.42055928, 0.2392846 , 0.10220312, 0.37898963],
       [0.41585617, 0.23706299, 0.59108179, 0.25581339, 0.37891709]])

In [16]:
np.random.randint(1,50)

28

In [17]:
np.random.randint(1,50,5)

array([30, 44, 45, 43, 48])

In [19]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
ranint=np.random.randint(0,30,10)
ranint

array([ 7,  3, 10, 18, 27,  0, 13, 27, 20,  9])

In [23]:
ranint.max()

27

In [24]:
ranint.argmin()

5

In [25]:
ranint.argmax()

4

In [28]:
arr.reshape(5,5)
arr=arr.reshape(5,5)
arr.shape

(5, 5)

In [29]:
arr.dtype

dtype('int64')

In [31]:
arr[:]=50
arr

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50]])

In [32]:
# Q.2 try to perform conditional operator like <,>  on the array .

In [33]:
my_array = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/titanic.csv',delimiter=",")

In [34]:
print(my_array)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [36]:
print(my_array.head(3))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  


In [37]:
my_array.to_csv('/content/drive/MyDrive/Colab Notebooks/my_pandas_dataframe.csv', index=False)

In [38]:
y=my_array.to_csv('/content/drive/MyDrive/Colab Notebooks/my_pandas_dataframe1.csv', index=False, columns=['PassengerId','Survived'])

In [39]:
y=my_array.to_csv('/content/drive/MyDrive/Colab Notebooks/my_pandas_dataframe2.csv', index=False,columns=['PassengerId','Survived'])

In [40]:
yy=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/my_pandas_dataframe2.csv')

In [41]:
print(yy.head(5))

   PassengerId  Survived
0            1         0
1            2         1
2            3         1
3            4         1
4            5         0


In [42]:
a_np_array=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=int)
a_np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
np.savetxt("/content/drive/MyDrive/Colab Notebooks/output.csv", a_np_array, delimiter=",")

In [44]:
a = np.array([[1, 6, 4],[2, 4, 8],[3, 9, 1]])
np.savetxt("/content/drive/MyDrive/Colab Notebooks/data3.csv", a, delimiter = ",")

In [45]:
# Q. Try to create csv file from above method from pandas , also use reshape function to covert the 1 d array in to 2 d array.Example:(arr = np.arange(1,11).reshape(2,5))

In [46]:
y = np.loadtxt("/content/drive/MyDrive/Colab Notebooks/output.csv",dtype=str)
y

array(['1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00',
       '4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00',
       '7.000000000000000000e+00,8.000000000000000000e+00,9.000000000000000000e+00'],
      dtype='<U74')

In [47]:
my= np.loadtxt('/content/drive/MyDrive/Colab Notebooks/2021.csv',delimiter=",", skiprows=1)

In [48]:
print (my[0:5,:])

[[ 1. 10. 22.]
 [ 2. 11. 23.]
 [ 3. 12. 24.]
 [ 4. 13. 25.]
 [ 5. 14. 26.]]


In [49]:
np.savetxt("/content/drive/MyDrive/Colab Notebooks/saved_numpy_data_1.csv", my[0:5,:], delimiter=",")

In [50]:
TT=my.astype(int)

In [51]:
np.savetxt("/content/drive/MyDrive/Colab Notebooks/SN.csv",TT,delimiter=",")